const vehicles = [{
  id: 1,
  model: 'toyota',
  type: 'sedan',
  year: '2017',
  modelname: 'senna',
  founder: 'kiichiro toyoda',
}, {
  id: 2,
  model: 'mercedes',
  type: 'SUV',
  year: '2020',
  modelname: 'gwagon',
  founder: 'karl benz',
}, {
  id: 3,
  model: 'lamborghini',
  type: 'super car',
  year: '2017',
  modelname: 'SV',
  founder: 'ferruccio lamborghini',
}, {
  id: 4,
  model: 'porsche',
  type: 'sports car',
  year: '2019',
  modelname: 'GT3 RS',
  founder: 'ferdinand porsche',
}, {
  id: 5,
  model: 'ferrari',
  type: 'super car',
  year: '2019',
  modelname: '812 superfast',
  founder: 'enzo ferrari',
}, {
  id: 6,
  model: 'Pagani',
  type: 'hyper car',
  year: '2019',
  modelname: 'huayra',
  founder: 'horacio pagani',
}, {
  id: 7,
  model: 'mclaren',
  type: 'super car',
  year: '2018',
  modelname: '720 S',
  founder: 'ron dennis',
}, {
  id: 8,
  model: 'honda',
  type: 'sedan',
  year: '2020',
  modelname: 'accord',
  founder: 'soichiro honda',
}, {
  id: 9,
  model: 'toyota',
  type: 'SUV',
  year: '2017',
  modelname: 'highlander',
  founder: 'kiichiro toyoda',
}, {
  id: 10,
  model: 'subaru',
  type: 'sedan',
  year: '2010',
  modelname: 'STI',
  founder: 'kenji kita',
}, {
  id: 11,
  model: 'koeinigsegg',
  type: 'mega car',
  year: '2020',
  modelname: 'jesko',
  founder: 'christian von koeinigsegg',
}, {
  id: 12,
  model: 'dodge',
  type: 'sports car',
  year: '2016',
  modelname: 'hellcat',
  founder: 'dodge brothers',
}, {
  id: 13,
  model: 'BMW',
  type: 'coupe',
  year: '2019',
  modelname: '335 i',
  founder: 'karl rapp',
}, {
  id: 14,
  model: 'porsche',
  type: 'SUV',
  year: '2020',
  modelname: 'cayenne',
  founder: 'ferdinand porsche',
}, {
  id: 15,
  model: 'chevrolet',
  type: 'sports car',
  year: '2018',
  modelname: 'corvette',
  founder: 'louis chevrolet',
}, {
  id: 16,
  model: 'bentley',
  type: 'SUV',
  year: '2019',
  modelname: 'bentayga',
  founder: 'bentley brothers',
}]

module.exports = vehicles
